# 2nd Day of Coding in Python 
print(2+3)
print()
print(3-2)
print()
print(2 + 3)
print(2  +  3)
print()
#Spaces in Operators are meaningless
print("Addition  + ")
print()
print(5+1)
print(2+2)
print()
print("Subtraction   -  ")
print()
print(2-1)
print(3-5)
print()
print("Multipication   *   ")
print()
print(2*8)
print(2 * 4)
print(2.2*2)
print()
print("Division    /    will give answer in decimal numbers  whereas   //   will give answer in whole numbers     ")
print()
print(4/4)
print(5/2)
print(5//2)
print(10/3)
print(10/2)
print()
print("Remainder    %   ")
print()
print(3%2)
print(10%3)
print(10%7)
print(2%2)
print()
print(" Exponentional or Power ")
print()
print(2**2)
print(3**2)
print(4**2)
print(2**3)
print(2.2**3)
print()
print("Remember that these all operators except the exponent or power    **   doesn't works in terminal. Why?")
print("Its because first we have to initialize the python in the terminal and then use the ** ")
#--------------------------------------------PEMDAS------Parentheses, Exponents, Multiply, Divide, Add, Subtract----------
# left to right Sequence for multipication, Division and Addition, subtration